In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [3]:
training_inputs = np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)

In [4]:
synaptic_weights = 2 * np.random.random((3,1)) - 1

In [5]:
print('Random starting synaptic weights: ')
synaptic_weights

Random starting synaptic weights: 


array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [6]:
# for iteration in range(1):
#     input_layer = training_inputs
#     outputs = sigmoid(np.dot(input_layer,synaptic_weights))
# print('Outputs after first training: ')
# print(outputs)

In [11]:
for iteration in range(100000):
    
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer,synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print('Synaptic weights after traning: ')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after traning: 
[[12.11491915]
 [-0.20432652]
 [-5.85345953]]
Outputs after training: 
[[0.00286175]
 [0.99766435]
 [0.99809517]
 [0.00233412]]
